/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/esheldon/local/src/nim-0.14.2/lib -o /home/esheldon/git/nimcode/src/images/nimcache/images.o /home/esheldon/git/nimcode/src/images/nimcache/images.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct Matrix64143220 Matrix64143220;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 Ordertype99407;
typedef struct {
N_NIMCALL_PTR(NF, ClPrc) (NI i0, NI j0, void* ClEnv);
void* ClEnv;
} TY122283;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Matrix64143220  {
Ordertype99407 order;
NF* data;
};
typedef NF TY143487[9];
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NF TY143587[6];
typedef N_NIMCALL_PTR(void, Globalmarkerproc56802) (void);
N_NIMCALL(void, randommatrix_143004_2092861038)(NF max0, Ordertype99407 order0, Matrix64143220* Result);
N_NIMCALL(void, makematrix_143025_2092861038)(TY122283 f0, Ordertype99407 order0, Matrix64143220* Result);
N_NIMCALL(void, makesmatrix_143204_2092861038)(TY122283 f0, Ordertype99407 order0, Matrix64143220* Result);
N_NIMCALL(NimStringDesc*, HEX24_143384_2092861038)(Matrix64143220 m0);
static N_INLINE(NF*, row_143443_2092861038)(Matrix64143220 m0, NI i0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NF, at_143527_2092861038)(Matrix64143220 m0, NI i0, NI j0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, tostringhorizontal_143609_2092861038)(NF* v0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, TMP1007)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc56802 markerproc0);
N_NOINLINE(void, chckNil)(void* p0);
N_NIMCALL(void, genericReset)(void* dest0, TNimType* mt0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimblas_nimblasInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimblas_nimblasDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, linalg_linalgInit000)(void);
NIM_EXTERNC N_NOINLINE(void, linalg_linalgDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, imagesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, imagesDatInit000)(void);
extern TNimType NTI143486; /* Vector64 */
extern TFrame* frameptr_19636_1689653243;
Matrix64143220 vm1_143382_1405198342;
extern TNimType NTI143220; /* Matrix64 */

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

static N_INLINE(NF, at_143527_2092861038)(Matrix64143220 m0, NI i0, NI j0) {
	NF result0;
	nimfr("at", "access.nim")
	result0 = (NF)0;
	nimln(50, "access.nim");
	nimln(39, "access.nim");
	{
		TY143587* data_143573_2092861038;
		if (!(m0.order == ((Ordertype99407) 102))) goto LA3;
		nimln(40, "access.nim");
		data_143573_2092861038 = ((TY143587*) (m0.data));
		if ((NU)(j0) > (NU)(8)) raiseIndexError();
		if ((NU)(i0) > (NU)(5)) raiseIndexError();
		result0 = data_143573_2092861038[(j0)- 0][(i0)- 0];
	}
	goto LA1;
	LA3: ;
	{
		TY143487* data_143575_2092861038;
		nimln(43, "access.nim");
		data_143575_2092861038 = ((TY143487*) (m0.data));
		if ((NU)(i0) > (NU)(5)) raiseIndexError();
		if ((NU)(j0) > (NU)(8)) raiseIndexError();
		result0 = data_143575_2092861038[(i0)- 0][(j0)- 0];
	}
	LA1: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NF*, row_143443_2092861038)(Matrix64143220 m0, NI i0) {
	NF* result0;
	nimfr("row", "access.nim")
	result0 = (NF*)0;
	nimln(134, "access.nim");
	result0 = (NF*) newObj((&NTI143486), sizeof(TY143487));
	{
		NI j_143525_2092861038;
		NI res_143604_2092861038;
		j_143525_2092861038 = (NI)0;
		nimln(1875, "system.nim");
		res_143604_2092861038 = ((NI) 0);
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP1006;
				if (!(res_143604_2092861038 <= ((NI) 8))) goto LA3;
				nimln(1877, "system.nim");
				j_143525_2092861038 = res_143604_2092861038;
				nimln(136, "access.nim");
				if ((NU)(j_143525_2092861038) > (NU)(8)) raiseIndexError();
				result0[(j_143525_2092861038)- 0] = at_143527_2092861038(m0, i0, j_143525_2092861038);
				nimln(1896, "system.nim");
				TMP1006 = addInt(res_143604_2092861038, ((NI) 1));
				res_143604_2092861038 = (NI)(TMP1006);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}
N_NIMCALL(void, TMP1007)() {
	nimGCvisit((void*)vm1_143382_1405198342.data, 0);
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_mathDatInit000();
	nimblas_nimblasDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_randomDatInit000();
	stdlib_sequtilsDatInit000();
	linalg_linalgDatInit000();
	imagesDatInit000();
	stdlib_mathInit000();
	nimblas_nimblasInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_randomInit000();
	stdlib_sequtilsInit000();
	linalg_linalgInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	imagesInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, imagesInit000)(void) {
	NimStringDesc* LOC1;
	nimfr("images", "images.nim")
nimRegisterGlobalMarker(TMP1007);
	nimln(6, "images.nim");
	chckNil((void*)(&vm1_143382_1405198342));
	genericReset((void*)(&vm1_143382_1405198342), (&NTI143220));
	randommatrix_143004_2092861038(1.0000000000000000e+00, ((Ordertype99407) 102), (&vm1_143382_1405198342));
	nimln(7, "images.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = HEX24_143384_2092861038(vm1_143382_1405198342);
	printf("%s\012", LOC1? (LOC1)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, imagesDatInit000)(void) {
}

