/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/esheldon/local/src/nim-0.14.2/lib -o /home/esheldon/git/nimcode/src/images/nimcache/nimblas_nimblas.o /home/esheldon/git/nimcode/src/images/nimcache/nimblas_nimblas.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, TY99419) (NI N0, NF32 Alpha0, NF32* X0, NI Incx0);
typedef N_CDECL_PTR(void, TY99426) (NI N0, NF Alpha0, NF* X0, NI Incx0);
typedef N_CDECL_PTR(void, TY99433) (NI N0, NF32* X0, NI Incx0, NF32* Y0, NI Incy0);
typedef N_CDECL_PTR(void, TY99442) (NI N0, NF* X0, NI Incx0, NF* Y0, NI Incy0);
typedef N_CDECL_PTR(void, TY99451) (NI N0, NF32 Alpha0, NF32* X0, NI Incx0, NF32* Y0, NI Incy0);
typedef N_CDECL_PTR(void, TY99461) (NI N0, NF Alpha0, NF* X0, NI Incx0, NF* Y0, NI Incy0);
typedef N_CDECL_PTR(NF32, TY99471) (NI N0, NF32* X0, NI Incx0, NF32* Y0, NI Incy0);
typedef N_CDECL_PTR(NF, TY99480) (NI N0, NF* X0, NI Incx0, NF* Y0, NI Incy0);
typedef N_CDECL_PTR(NF32, TY99489) (NI N0, NF32* X0, NI Incx0);
typedef N_CDECL_PTR(NF, TY99495) (NI N0, NF* X0, NI Incx0);
typedef N_CDECL_PTR(NF32, TY99501) (NI N0, NF32* X0, NI Incx0);
typedef N_CDECL_PTR(NF, TY99507) (NI N0, NF* X0, NI Incx0);
typedef NU8 Ordertype99407;
typedef NU8 Transposetype99405;
typedef N_CDECL_PTR(void, TY99513) (Ordertype99407 Order0, Transposetype99405 Trans0, NI M0, NI N0, NF32 Alpha0, NF32* A0, NI Lda0, NF32* X0, NI Incx0, NF32 Beta0, NF32* Y0, NI Incy0);
typedef N_CDECL_PTR(void, TY99530) (Ordertype99407 Order0, Transposetype99405 Trans0, NI M0, NI N0, NF Alpha0, NF* A0, NI Lda0, NF* X0, NI Incx0, NF Beta0, NF* Y0, NI Incy0);
typedef N_CDECL_PTR(void, TY99547) (Ordertype99407 Order0, Transposetype99405 Transa0, Transposetype99405 Transb0, NI M0, NI N0, NI K0, NF32 Alpha0, NF32* A0, NI Lda0, NF32* B0, NI Ldb0, NF32 Beta0, NF32* C0, NI Ldc0);
typedef N_CDECL_PTR(void, TY99566) (Ordertype99407 Order0, Transposetype99405 Transa0, Transposetype99405 Transb0, NI M0, NI N0, NI K0, NF Alpha0, NF* A0, NI Lda0, NF* B0, NI Ldb0, NF Beta0, NF* C0, NI Ldc0);
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP157, "libblas.so", 10);
STRING_LITERAL(TMP158, "libblas.so", 10);
static void* TMP156;
TY99419 Dl_99418;
TY99426 Dl_99425;
TY99433 Dl_99432;
TY99442 Dl_99441;
TY99451 Dl_99450;
TY99461 Dl_99460;
TY99471 Dl_99470;
TY99480 Dl_99479;
TY99489 Dl_99488;
TY99495 Dl_99494;
TY99501 Dl_99500;
TY99507 Dl_99506;
TY99513 Dl_99512;
TY99530 Dl_99529;
TY99547 Dl_99546;
TY99566 Dl_99565;
TNimType NTI99407; /* OrderType */
extern TFrame* frameptr_19636_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}
NIM_EXTERNC N_NOINLINE(void, nimblas_nimblasInit000)(void) {
	nimfr("nimblas", "nimblas.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimblas_nimblasDatInit000)(void) {
static TNimNode* TMP643[2];
NI TMP645;
static char* NIM_CONST TMP644[2] = {
"rowMajor", 
"colMajor"};
static TNimNode TMP154[3];
NTI99407.size = sizeof(Ordertype99407);
NTI99407.kind = 14;
NTI99407.base = 0;
NTI99407.flags = 3;
for (TMP645 = 0; TMP645 < 2; TMP645++) {
TMP154[TMP645+0].kind = 1;
TMP154[TMP645+0].offset = TMP645;
TMP154[TMP645+0].name = TMP644[TMP645];
TMP643[TMP645] = &TMP154[TMP645+0];
}
TMP154[0].offset = 101;
TMP154[1].offset = 102;
TMP154[2].len = 2; TMP154[2].kind = 2; TMP154[2].sons = &TMP643[0];
NTI99407.node = &TMP154[2];
NTI99407.flags = 1<<2;
if (!((TMP156 = nimLoadLibrary((NimStringDesc*) &TMP157))
)) nimLoadLibraryError((NimStringDesc*) &TMP158);
	Dl_99418 = (TY99419) nimGetProcAddr(TMP156, "cblas_sscal");
	Dl_99425 = (TY99426) nimGetProcAddr(TMP156, "cblas_dscal");
	Dl_99432 = (TY99433) nimGetProcAddr(TMP156, "cblas_scopy");
	Dl_99441 = (TY99442) nimGetProcAddr(TMP156, "cblas_dcopy");
	Dl_99450 = (TY99451) nimGetProcAddr(TMP156, "cblas_saxpy");
	Dl_99460 = (TY99461) nimGetProcAddr(TMP156, "cblas_daxpy");
	Dl_99470 = (TY99471) nimGetProcAddr(TMP156, "cblas_sdot");
	Dl_99479 = (TY99480) nimGetProcAddr(TMP156, "cblas_ddot");
	Dl_99488 = (TY99489) nimGetProcAddr(TMP156, "cblas_snrm2");
	Dl_99494 = (TY99495) nimGetProcAddr(TMP156, "cblas_dnrm2");
	Dl_99500 = (TY99501) nimGetProcAddr(TMP156, "cblas_sasum");
	Dl_99506 = (TY99507) nimGetProcAddr(TMP156, "cblas_dasum");
	Dl_99512 = (TY99513) nimGetProcAddr(TMP156, "cblas_sgemv");
	Dl_99529 = (TY99530) nimGetProcAddr(TMP156, "cblas_dgemv");
	Dl_99546 = (TY99547) nimGetProcAddr(TMP156, "cblas_sgemm");
	Dl_99565 = (TY99566) nimGetProcAddr(TMP156, "cblas_dgemm");
}

