/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/esheldon/local/src/nim-0.14.2/lib -o /home/esheldon/git/nimcode/src/images/nimcache/stdlib_random.o /home/esheldon/git/nimcode/src/images/nimcache/stdlib_random.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <time.h>
typedef struct Randomgenstate101402 Randomgenstate101402;
struct  Randomgenstate101402  {
NU64 a0;
NU64 a1;
};
typedef NU64 TY101802[2];
N_NIMCALL(NU64, rotl_101602_4293377359)(NU64 x0, NU64 k0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NU64, next_101644_4293377359)(Randomgenstate101402* s0);
N_NIMCALL(void, skiprandomnumbers_101698_4293377359)(Randomgenstate101402* s0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, random_102097_4293377359)(NI max0);
N_NIMCALL(NF, random_102113_4293377359)(NF max0);
N_NIMCALL(void, randomize_102252_4293377359)(NI seed0);
N_NIMCALL(void, randomize_118001_4293377359)(void);
N_NIMCALL(time_t, gettime_113637_2726502234)(void);
NIM_CONST TY101802 helper_101801_4293377359 = {13739361407582206667ULL,
15594563132006766882ULL}
;
Randomgenstate101402 state_101405_4293377359;
extern TFrame* frameptr_19636_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

N_NIMCALL(NU64, rotl_101602_4293377359)(NU64 x0, NU64 k0) {
	NU64 result0;
	nimfr("rotl", "random.nim")
	result0 = (NU64)0;
	nimln(40, "random.nim");
	result0 = (NU64)((NU64)((NU64)(x0) << (NU64)(k0)) | (NU64)((NU64)(x0) >> (NU64)((NU64)((NU64)(64ULL) - (NU64)(k0)))));
	popFrame();
	return result0;
}

N_NIMCALL(NU64, next_101644_4293377359)(Randomgenstate101402* s0) {
	NU64 result0;
	NU64 s00;
	NU64 s10;
	NU64 LOC1;
	nimfr("next", "random.nim")
	result0 = (NU64)0;
	nimln(43, "random.nim");
	s00 = (*s0).a0;
	nimln(44, "random.nim");
	s10 = (*s0).a1;
	nimln(45, "random.nim");
	result0 = (NU64)((NU64)(s00) + (NU64)(s10));
	nimln(46, "random.nim");
	s10 = (NU64)(s10 ^ s00);
	nimln(47, "random.nim");
	LOC1 = (NU64)0;
	LOC1 = rotl_101602_4293377359(s00, 55ULL);
	(*s0).a0 = (NU64)((NU64)(LOC1 ^ s10) ^ (NU64)((NU64)(s10) << (NU64)(((NI) 14))));
	nimln(48, "random.nim");
	(*s0).a1 = rotl_101602_4293377359(s10, 36ULL);
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, skiprandomnumbers_101698_4293377359)(Randomgenstate101402* s0) {
	NU64 s00;
	NU64 s10;
	nimfr("skipRandomNumbers", "random.nim")
	nimln(59, "random.nim");
	s00 = 0ULL;
	nimln(60, "random.nim");
	s10 = 0ULL;
	{
		NI i_102014_4293377359;
		NI res_102094_4293377359;
		i_102014_4293377359 = (NI)0;
		nimln(1875, "system.nim");
		res_102094_4293377359 = ((NI) 0);
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP162;
				if (!(res_102094_4293377359 <= ((NI) 1))) goto LA3;
				nimln(1877, "system.nim");
				i_102014_4293377359 = ((NI)chckRange(res_102094_4293377359, ((NI) 0), ((NI) 1)));
				{
					NI b_102036_4293377359;
					NI i_102090_4293377359;
					b_102036_4293377359 = (NI)0;
					nimln(3607, "system.nim");
					i_102090_4293377359 = ((NI) 0);
					{
						nimln(3608, "system.nim");
						while (1) {
							NU64 LOC11;
							NI TMP161;
							if (!(i_102090_4293377359 < ((NI) 64))) goto LA6;
							nimln(3607, "system.nim");
							b_102036_4293377359 = i_102090_4293377359;
							nimln(63, "random.nim");
							{
								nimln(343, "system.nim");
								nimln(63, "random.nim");
								if (!!(((NU64)(helper_101801_4293377359[(i_102014_4293377359)- 0] & (NU64)((NU64)(1ULL) << (NU64)(((NU64) (b_102036_4293377359))))) == ((NI) 0)))) goto LA9;
								nimln(64, "random.nim");
								s00 = (NU64)(s00 ^ (*s0).a0);
								nimln(65, "random.nim");
								s10 = (NU64)(s10 ^ (*s0).a1);
							}
							LA9: ;
							nimln(66, "random.nim");
							LOC11 = (NU64)0;
							LOC11 = next_101644_4293377359(s0);
							nimln(3610, "system.nim");
							TMP161 = addInt(i_102090_4293377359, ((NI) 1));
							i_102090_4293377359 = (NI)(TMP161);
						} LA6: ;
					}
				}
				nimln(1896, "system.nim");
				TMP162 = addInt(res_102094_4293377359, ((NI) 1));
				res_102094_4293377359 = (NI)(TMP162);
			} LA3: ;
		}
	}
	nimln(67, "random.nim");
	(*s0).a0 = s00;
	nimln(68, "random.nim");
	(*s0).a1 = s10;
	popFrame();
}

N_NIMCALL(NI, random_102097_4293377359)(NI max0) {
	NI result0;
	NU64 LOC1;
	nimfr("random", "random.nim")
	result0 = (NI)0;
	nimln(75, "random.nim");
	LOC1 = (NU64)0;
	LOC1 = next_101644_4293377359((&state_101405_4293377359));
	result0 = ((NI) ((NU64)((NU64)(LOC1) % (NU64)(((NU64) (max0))))));
	popFrame();
	return result0;
}

N_NIMCALL(NF, random_102113_4293377359)(NF max0) {
	NF result0;
	NU64 x0;
	NU64 u0;
	union { NU64 source; NF dest; } LOC1;
	nimfr("random", "random.nim")
	result0 = (NF)0;
	nimln(82, "random.nim");
	x0 = next_101644_4293377359((&state_101405_4293377359));
	nimln(86, "random.nim");
	u0 = (NU64)(4607182418800017408ULL | (NU64)((NU64)(x0) >> (NU64)(12ULL)));
	nimln(87, "random.nim");
	LOC1.source = u0;
	result0 = ((NF)(((NF)(LOC1.dest) - (NF)(1.0000000000000000e+00))) * (NF)(max0));
	popFrame();
	return result0;
}

N_NIMCALL(void, randomize_102252_4293377359)(NI seed0) {
	nimfr("randomize", "random.nim")
	nimln(99, "random.nim");
	state_101405_4293377359.a0 = ((NU64) ((NI)((NU64)(seed0) >> (NU64)(((NI) 16)))));
	nimln(100, "random.nim");
	state_101405_4293377359.a1 = ((NU64) ((NI)(seed0 & ((NI) 65535))));
	popFrame();
}

N_NIMCALL(void, randomize_118001_4293377359)(void) {
	time_t LOC1;
	nimfr("randomize", "random.nim")
	nimln(112, "random.nim");
	LOC1 = (time_t)0;
	LOC1 = gettime_113637_2726502234();
	randomize_102252_4293377359(LOC1);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void) {
	Randomgenstate101402 LOC1;
	nimfr("random", "random.nim")
	nimln(35, "random.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.a0 = 7616934476015405061ULL;
	LOC1.a1 = 15122295919272093642ULL;
	state_101405_4293377359 = LOC1;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void) {
}

