/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/esheldon/local/src/nim-0.14.2/lib -o /home/esheldon/git/nimcode/src/images/nimcache/stdlib_strutils.o /home/esheldon/git/nimcode/src/images/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Slice90651 Slice90651;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Valueerror3446 Valueerror3446;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell48305 Cell48305;
typedef struct Cellseq48321 Cellseq48321;
typedef struct Gcheap50818 Gcheap50818;
typedef struct Gcstack50816 Gcstack50816;
typedef struct Memregion30486 Memregion30486;
typedef struct Smallchunk30440 Smallchunk30440;
typedef struct Llchunk30480 Llchunk30480;
typedef struct Bigchunk30442 Bigchunk30442;
typedef struct Intset30414 Intset30414;
typedef struct Trunk30410 Trunk30410;
typedef struct Avlnode30484 Avlnode30484;
typedef struct Gcstat50814 Gcstat50814;
typedef struct Cellset48317 Cellset48317;
typedef struct Pagedesc48313 Pagedesc48313;
typedef struct Basechunk30438 Basechunk30438;
typedef struct Freecell30430 Freecell30430;
struct  Slice90651  {
NI a;
NI b;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3446  {
  Exception Sup;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell48305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48321  {
NI len;
NI cap;
Cell48305** d;
};
typedef Smallchunk30440* TY30501[512];
typedef Trunk30410* Trunkbuckets30412[256];
struct  Intset30414  {
Trunkbuckets30412 data;
};
struct  Memregion30486  {
NI minlargeobj;
NI maxlargeobj;
TY30501 freesmallchunks;
Llchunk30480* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30442* freechunkslist;
Intset30414 chunkstarts;
Avlnode30484* root;
Avlnode30484* deleted;
Avlnode30484* last;
Avlnode30484* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset48317  {
NI counter;
NI max;
Pagedesc48313* head;
Pagedesc48313** data;
};
struct  Gcheap50818  {
Gcstack50816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48321 zct;
Cellseq48321 decstack;
Cellseq48321 tempstack;
NI recgclock;
Memregion30486 region;
Gcstat50814 stat;
Cellset48317 marked;
Cellseq48321 additionalroots;
};
struct  Gcstack50816  {
Gcstack50816* prev;
Gcstack50816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30438  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30440  {
  Basechunk30438 Sup;
Smallchunk30440* next;
Smallchunk30440* prev;
Freecell30430* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30480  {
NI size;
NI acc;
Llchunk30480* next;
};
struct  Bigchunk30442  {
  Basechunk30438 Sup;
Bigchunk30442* next;
Bigchunk30442* prev;
NI align;
NF data;
};
typedef NI TY30419[8];
struct  Trunk30410  {
Trunk30410* next;
NI key;
TY30419 bits;
};
typedef Avlnode30484* TY30491[2];
struct  Avlnode30484  {
TY30491 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc48313  {
Pagedesc48313* next;
NI key;
TY30419 bits;
};
struct  Freecell30430  {
Freecell30430* next;
NI zerofield;
};
static N_INLINE(NIM_BOOL, contains_110475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
static N_INLINE(NI, find_110485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, contains_110650_1689653243)(Slice90651 s0, NI value0);
N_NIMCALL(NF, round_110661_1009420244)(NF x0, NI places0);
static N_INLINE(void, HEX2AHEX3D_110691_1689653243)(NF* x0, NF y0);
static N_INLINE(void, HEX2BHEX3D_110701_1689653243)(NF* x0, NF y0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s0, NI* number0, NI start0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell48305*, usrtocell_52440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53601_1689653243)(Cell48305* c0);
N_NOINLINE(void, addzct_52417_1689653243)(Cellseq48321* s0, Cell48305* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c0);
N_NIMCALL(NIM_CHAR, nsuToUpperChar)(NIM_CHAR c0);
STRING_LITERAL(TMP371, "invalid integer: ", 17);
extern TFrame* frameptr_19636_1689653243;
extern TNimType NTI24225; /* ref ValueError */
extern TNimType NTI3446; /* ValueError */
extern Gcheap50818 gch_50858_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

static N_INLINE(NI, find_110485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		NIM_CHAR i_110519_1689653243;
		NI i_110532_1689653243;
		i_110519_1689653243 = (NIM_CHAR)0;
		nimln(1966, "system.nim");
		i_110532_1689653243 = ((NI) 0);
		{
			nimln(1967, "system.nim");
			while (1) {
				NI TMP169;
				NI TMP170;
				if (!(i_110532_1689653243 < a0Len0)) goto LA3;
				nimln(1968, "system.nim");
				if ((NU)(i_110532_1689653243) >= (NU)(a0Len0)) raiseIndexError();
				i_110519_1689653243 = a0[i_110532_1689653243];
				nimln(2191, "system.nim");
				{
					if (!((NU8)(i_110519_1689653243) == (NU8)(item0))) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2192, "system.nim");
				TMP169 = addInt(result0, ((NI) 1));
				result0 = (NI)(TMP169);
				nimln(1969, "system.nim");
				TMP170 = addInt(i_110532_1689653243, ((NI) 1));
				i_110532_1689653243 = (NI)(TMP170);
			} LA3: ;
		}
	}
	nimln(2193, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_110475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NIM_BOOL result0;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result0 = (NIM_BOOL)0;
	nimln(2198, "system.nim");
	nimln(346, "system.nim");
	nimln(347, "system.nim");
	nimln(2198, "system.nim");
	LOC1 = (NI)0;
	LOC1 = find_110485_1689653243(a0, a0Len0, item0);
	result0 = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_110650_1689653243)(Slice90651 s0, NI value0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("contains", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(1093, "system.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) (s0.a)) <= ((NI) (value0)));
	if (!(LOC1)) goto LA2;
	LOC1 = (((NI) (value0)) <= ((NI) (s0.b)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_110691_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3324, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_110701_1689653243)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3314, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0) {
	(*dest0).data[((*dest0).Sup.len)- 0] = c0;
	(*dest0).data[((NI)((*dest0).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest0).Sup.len += ((NI) 1);
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	memcpy(((NCSTRING) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((NCSTRING) ((*src0).data)), (NI)((*src0).Sup.len + ((NI) 1)));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x0, NI minchars0) {
	NimStringDesc* result0;
	nimfr("intToStr", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = nimIntToStr((x0 > 0? (x0) : -(x0)));
	{
		NI i_107646_4286263276;
		NI HEX3Atmp_107648_4286263276;
		NI res_107651_4286263276;
		i_107646_4286263276 = (NI)0;
		HEX3Atmp_107648_4286263276 = (NI)0;
		HEX3Atmp_107648_4286263276 = (NI)(((NI) (minchars0)) - (result0 ? result0->Sup.len : 0));
		res_107651_4286263276 = ((NI) 1);
		{
			while (1) {
				NimStringDesc* LOC4;
				if (!(res_107651_4286263276 <= HEX3Atmp_107648_4286263276)) goto LA3;
				i_107646_4286263276 = res_107651_4286263276;
				LOC4 = (NimStringDesc*)0;
				LOC4 = rawNewString(result0->Sup.len + 1);
appendChar(LOC4, 48);
appendString(LOC4, result0);
				result0 = LOC4;
				res_107651_4286263276 += ((NI) 1);
			} LA3: ;
		}
	}
	{
		NimStringDesc* LOC9;
		if (!(x0 < ((NI) 0))) goto LA7;
		LOC9 = (NimStringDesc*)0;
		LOC9 = rawNewString(result0->Sup.len + 1);
appendChar(LOC9, 45);
appendString(LOC9, result0);
		result0 = LOC9;
	}
	LA7: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c0, NI count0) {
	NimStringDesc* result0;
	nimfr("repeat", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = mnewString(count0);
	{
		NI i_107944_4286263276;
		NI HEX3Atmp_107946_4286263276;
		NI res_107949_4286263276;
		i_107944_4286263276 = (NI)0;
		HEX3Atmp_107946_4286263276 = (NI)0;
		HEX3Atmp_107946_4286263276 = (NI)(((NI) (count0)) - ((NI) 1));
		res_107949_4286263276 = ((NI) 0);
		{
			while (1) {
				if (!(res_107949_4286263276 <= ((NI) (HEX3Atmp_107946_4286263276)))) goto LA3;
				i_107944_4286263276 = ((NI) (res_107949_4286263276));
				result0->data[i_107944_4286263276] = c0;
				res_107949_4286263276 += ((NI) 1);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

static N_INLINE(Cell48305*, usrtocell_52440_1689653243)(void* usr0) {
	Cell48305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell48305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell48305*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell48305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53601_1689653243)(Cell48305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_52417_1689653243((&gch_50858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell48305* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_52440_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell48305* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_52440_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_53601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0) {
	NI result0;
	NI L0;
	nimfr("parseInt", "strutils.nim")
	result0 = (NI)0;
	L0 = npuParseInt(s0, (&result0), ((NI) 0));
	{
		NIM_BOOL LOC3;
		Valueerror3446* e_107664_4286263276;
		NimStringDesc* LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !((L0 == (s0 ? s0->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L0 == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_107664_4286263276 = (Valueerror3446*)0;
		e_107664_4286263276 = (Valueerror3446*) newObj((&NTI24225), sizeof(Valueerror3446));
		(*e_107664_4286263276).Sup.Sup.m_type = (&NTI3446);
		LOC7 = (NimStringDesc*)0;
		LOC7 = rawNewString(s0->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &TMP371));
appendString(LOC7, s0);
		asgnRefNoCycle((void**) (&(*e_107664_4286263276).Sup.message), LOC7);
		raiseException((Exception*)e_107664_4286263276, "ValueError");
	}
	LA5: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_CHAR, nsuToLowerChar)(NIM_CHAR c0) {
	NIM_CHAR result0;
	nimfr("toLower", "strutils.nim")
	result0 = (NIM_CHAR)0;
	nimln(199, "strutils.nim");
	{
		NI TMP375;
		nimln(1095, "system.nim");
		if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA3;
		nimln(200, "strutils.nim");
		TMP375 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
		result0 = ((NIM_CHAR) (((NI)chckRange((NI)(TMP375), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(202, "strutils.nim");
		result0 = c0;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s0) {
	NimStringDesc* result0;
	nimfr("toLower", "strutils.nim")
	result0 = (NimStringDesc*)0;
	nimln(211, "strutils.nim");
	result0 = mnewString(((NI)chckRange((s0 ? s0->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_106445_4286263276;
		NI HEX3Atmp_106447_4286263276;
		NI TMP374;
		NI res_106450_4286263276;
		i_106445_4286263276 = (NI)0;
		HEX3Atmp_106447_4286263276 = (NI)0;
		nimln(212, "strutils.nim");
		TMP374 = subInt((s0 ? s0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_106447_4286263276 = (NI)(TMP374);
		nimln(1875, "system.nim");
		res_106450_4286263276 = ((NI) 0);
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP376;
				if (!(res_106450_4286263276 <= HEX3Atmp_106447_4286263276)) goto LA3;
				nimln(1877, "system.nim");
				i_106445_4286263276 = res_106450_4286263276;
				nimln(213, "strutils.nim");
				if ((NU)(i_106445_4286263276) > (NU)(result0->Sup.len)) raiseIndexError();
				if ((NU)(i_106445_4286263276) > (NU)(s0->Sup.len)) raiseIndexError();
				result0->data[i_106445_4286263276] = nsuToLowerChar(s0->data[i_106445_4286263276]);
				nimln(1896, "system.nim");
				TMP376 = addInt(res_106450_4286263276, ((NI) 1));
				res_106450_4286263276 = (NI)(TMP376);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a0, NimStringDesc* b0) {
	NI result0;
	NI i0;
	NI m0;
	NI TMP391;
	nimfr("cmpIgnoreCase", "strutils.nim")
{	result0 = (NI)0;
	nimln(269, "strutils.nim");
	i0 = ((NI) 0);
	nimln(270, "strutils.nim");
	m0 = (((a0 ? a0->Sup.len : 0) <= (b0 ? b0->Sup.len : 0)) ? (a0 ? a0->Sup.len : 0) : (b0 ? b0->Sup.len : 0));
	{
		nimln(271, "strutils.nim");
		while (1) {
			NIM_CHAR LOC3;
			NIM_CHAR LOC4;
			NI TMP389;
			NI TMP390;
			if (!(i0 < m0)) goto LA2;
			nimln(272, "strutils.nim");
			if ((NU)(i0) > (NU)(a0->Sup.len)) raiseIndexError();
			LOC3 = (NIM_CHAR)0;
			LOC3 = nsuToLowerChar(a0->data[i0]);
			if ((NU)(i0) > (NU)(b0->Sup.len)) raiseIndexError();
			LOC4 = (NIM_CHAR)0;
			LOC4 = nsuToLowerChar(b0->data[i0]);
			TMP389 = subInt(((NI) (((NU8)(LOC3)))), ((NI) (((NU8)(LOC4)))));
			result0 = (NI)(TMP389);
			nimln(273, "strutils.nim");
			{
				nimln(343, "system.nim");
				if (!!((result0 == ((NI) 0)))) goto LA7;
				nimln(273, "strutils.nim");
				goto BeforeRet;
			}
			LA7: ;
			nimln(274, "strutils.nim");
			TMP390 = addInt(i0, ((NI) 1));
			i0 = (NI)(TMP390);
		} LA2: ;
	}
	nimln(275, "strutils.nim");
	TMP391 = subInt((a0 ? a0->Sup.len : 0), (b0 ? b0->Sup.len : 0));
	result0 = (NI)(TMP391);
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_CHAR, nsuToUpperChar)(NIM_CHAR c0) {
	NIM_CHAR result0;
	nimfr("toUpper", "strutils.nim")
	result0 = (NIM_CHAR)0;
	nimln(222, "strutils.nim");
	{
		NI TMP533;
		nimln(1095, "system.nim");
		if (!(((NU8)(c0)) >= ((NU8)(97)) && ((NU8)(c0)) <= ((NU8)(122)))) goto LA3;
		nimln(223, "strutils.nim");
		TMP533 = subInt(((NI) (((NU8)(c0)))), ((NI) 32));
		result0 = ((NIM_CHAR) (((NI)chckRange((NI)(TMP533), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(225, "strutils.nim");
		result0 = c0;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s0) {
	NimStringDesc* result0;
	nimfr("toUpper", "strutils.nim")
	result0 = (NimStringDesc*)0;
	nimln(234, "strutils.nim");
	result0 = mnewString(((NI)chckRange((s0 ? s0->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_106509_4286263276;
		NI HEX3Atmp_106511_4286263276;
		NI TMP532;
		NI res_106514_4286263276;
		i_106509_4286263276 = (NI)0;
		HEX3Atmp_106511_4286263276 = (NI)0;
		nimln(235, "strutils.nim");
		TMP532 = subInt((s0 ? s0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_106511_4286263276 = (NI)(TMP532);
		nimln(1875, "system.nim");
		res_106514_4286263276 = ((NI) 0);
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP534;
				if (!(res_106514_4286263276 <= HEX3Atmp_106511_4286263276)) goto LA3;
				nimln(1877, "system.nim");
				i_106509_4286263276 = res_106514_4286263276;
				nimln(236, "strutils.nim");
				if ((NU)(i_106509_4286263276) > (NU)(result0->Sup.len)) raiseIndexError();
				if ((NU)(i_106509_4286263276) > (NU)(s0->Sup.len)) raiseIndexError();
				result0->data[i_106509_4286263276] = nsuToUpperChar(s0->data[i_106509_4286263276]);
				nimln(1896, "system.nim");
				TMP534 = addInt(res_106514_4286263276, ((NI) 1));
				res_106514_4286263276 = (NI)(TMP534);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

